# Generated by Django 4.2.1 on 2024-07-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_usermodel_options_alter_usermodel_number_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='foydalavchilar',
        ),
    ]
